#!/bin/bash

. colors-def

bspc monitor -d term web code misc

bspc config border_width 1
bspc config window_gap 4
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 20

# application rules
bspc rule -a chromium desktop=web

bspc config focused_border_color "#$COL9"
bspc config normal_border_color "#$COL0"
bspc config presel_border_color "#$COL1"
