#!/bin/bash

. color-scheme

bspc monitor -d 001 010 011 100

bspc config border_width 1
bspc config window_gap 4
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 16

# application rules
bspc rule -a Chromium desktop=^4

bspc config focused_border_color "#$COL9"
bspc config normal_border_color "#$COL0"
bspc config presel_border_color "#$COL1"
