#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded,
# with the name of the image file as its first argument.
# The output is displayed in sxiv's status bar.

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry=$(identify -format '%wx%h' -- "$1[0]")

echo "${filesize} | ${geometry} | ${filename}"

