#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument and the path of the
# current image as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
  "1")
    imlibsetroot -s w "$2"
    ;;
  "2")
    imlibsetroot -s h "$2"
    ;;
  "3")
    imlibsetroot -s h -p c "$2"
   ;;
  "4")
    imlibsetroot -s -p cx "$2"
    ;;
  "5")
    imlibsetroot -s -p cy "$2"
    ;;
  "y")
    echo -n "$2" | xsel -b -i
    ;;
  "d")
    rm "$2"
    ;;
  "r")
    mv "$2" "${2%/*}/$(echo "${2##*/}" | dmenu)"
esac

