#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument and the path of the
# current image as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
  "w")
    imlibsetroot -s w "$2"
    ;;
  "h")
    imlibsetroot -s h "$2"
    ;;
  "c")
    imlibsetroot -s -p c "$2"
   ;;
  "x")
    imlibsetroot -s -p cx "$2"
    ;;
  "y")
    imlibsetroot -s -p cy "$2"
    ;;
  "C-y")
    echo -n "$2" | xsel -b -i
    ;;
  "C-d")
    rm $2
    ;;
esac

